// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/express-myconnection/express-myconnection.d.ts
declare namespace mysql{
  export interface IConnection {}
  export interface IError {}
}

declare namespace Express {

  export interface Request {
    getConnection?: (callback: (err: mysql.IError, connection: mysql.IConnection) => void) => void;
  }
}

declare module "express-myconnection" {
  import express = require('express');
  import mysql = require('mysql');

  function connection(mysql: mysql.IMySql, dbConfig: mysql.IConnectionConfig, strategy: string): express.RequestHandler;

  export = connection;
}
